services:
  bluetify:
    build: .
    environment:
      # spotify or lastfm
      - MUSIC_SERVICE=spotify
      # required MUSIC_SERVICE=spotify
      - SPOTIFY_CLIENT_ID=123456790qwerty
      - SPOTIFY_CLIENT_SECRET=qwerty123456790
      - SPOTIFY_REFRESH_TOKEN=token
      # required MUSIC_SERVICE=lastfm
      - LASTFM_API_KEY=qwe123456790rty
      - LASTFM_USERNAME=unicodick
      - BSKY_USERNAME=idontshitpost.lol
      - BSKY_PASSWORD=passwordlol
      - UPDATE_INTERVAL=30
    restart: unless-stopped
    container_name: bluetify-bot
